import type { Metadata } from 'next';
import { Providers } from './providers';
import Sidebar from '@/components/Sidebar';
import { getSession } from '@/utils/fetch/server';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getSession();

  return (
    <html lang='fr'>
      <body>
        <Providers session={session}>{session ? <Sidebar>{children}</Sidebar> : children}</Providers>
      </body>
    </html>
  );
}
